using System.Text;
using UnityCli.Protocol;

namespace UnityCli.DocGen;

public static class CliReferenceDocumentRenderer
{
    public const string OutputRelativePath = "docs/cli-reference.md";

    private static readonly CliCommandGroup[] CommandGroups =
    {
        CliCommandGroup.EditorControl,
        CliCommandGroup.AssetWorkflows,
        CliCommandGroup.SceneWorkflows,
        CliCommandGroup.PrefabWorkflows,
        CliCommandGroup.PackageManagement,
        CliCommandGroup.MaterialWorkflows,
        CliCommandGroup.InstanceManagement,
        CliCommandGroup.Diagnostics,
    };

    public static string Render()
    {
        CliCommandDescriptor[] commands = CliCommandCatalog.GetCommands();
        AssetCreateTypeDescriptor[] assetTypes = BuiltInAssetCreateCatalog.GetDescriptors();

        var builder = new StringBuilder();
        builder.AppendLine("<!-- Generated by `dotnet run --project cli/UnityCli.DocGen -- --write`. Do not edit by hand. -->");
        builder.AppendLine();
        builder.AppendLine("# CLI Reference");
        builder.AppendLine();
        builder.AppendLine("> Regenerate with `dotnet run --project cli/UnityCli.DocGen -- --write`.");
        builder.AppendLine();
        builder.AppendLine("## Summary");
        builder.AppendLine();
        builder.AppendLine("This document describes the repo-shipped `unity-cli` command surface in one place.");
        builder.AppendLine("It is generated from the shared command catalog and the built-in `asset create` catalog.");
        builder.AppendLine("Project-specific extension providers can still add more `asset create` types at runtime; those are intentionally out of scope for this generated baseline.");
        builder.AppendLine();
        builder.AppendLine("## Transport Modes");
        builder.AppendLine();
        builder.AppendLine("- `local`: resolved inside the CLI without Unity IPC.");
        builder.AppendLine("- `live`: executed against a running Unity Editor over local IPC.");
        builder.AppendLine();

        foreach (CliCommandGroup group in CommandGroups)
        {
            AppendCommandSection(builder, group, commands);
        }

        AppendAssetTypesSection(builder, assetTypes);
        AppendSafetySection(builder);
        AppendRelatedDocsSection(builder);

        return builder.ToString().TrimEnd() + Environment.NewLine;
    }

    private static void AppendCommandSection(
        StringBuilder builder,
        CliCommandGroup group,
        IEnumerable<CliCommandDescriptor> allCommands)
    {
        CliCommandDescriptor[] commands = allCommands.Where(command => command.Group == group).ToArray();
        if (commands.Length == 0)
        {
            return;
        }

        builder.AppendLine("## " + GetGroupTitle(group));
        builder.AppendLine();
        builder.AppendLine(GetGroupSummary(group));
        builder.AppendLine();
        builder.AppendLine("| Command | Synopsis | Modes | Summary |");
        builder.AppendLine("| --- | --- | --- | --- |");

        foreach (CliCommandDescriptor command in commands)
        {
            builder.Append("| ");
            builder.Append(EscapeTableCell("`" + command.Command + "`"));
            builder.Append(" | ");
            builder.Append(EscapeTableCell("`" + command.Synopsis + "`"));
            builder.Append(" | ");
            builder.Append(EscapeTableCell(FormatModes(command)));
            builder.Append(" | ");
            builder.Append(EscapeTableCell(command.Summary));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
    }

    private static void AppendAssetTypesSection(StringBuilder builder, IEnumerable<AssetCreateTypeDescriptor> assetTypes)
    {
        builder.AppendLine("## Built-In Asset Create Types");
        builder.AppendLine();
        builder.AppendLine("These are the built-in `asset create --type` targets shipped by this repo.");
        builder.AppendLine("Runtime extension providers can add more rows to `asset types`, but they are not part of the generated baseline below.");
        builder.AppendLine();
        builder.AppendLine("| Type | Aliases | Extension | Required | Optional | Data patch | Notes |");
        builder.AppendLine("| --- | --- | --- | --- | --- | --- | --- |");

        foreach (AssetCreateTypeDescriptor type in assetTypes)
        {
            builder.Append("| ");
            builder.Append(EscapeTableCell("`" + type.typeId + "`"));
            builder.Append(" | ");
            builder.Append(EscapeTableCell(FormatCodeList(type.aliases)));
            builder.Append(" | ");
            builder.Append(EscapeTableCell("`" + type.defaultExtension + "`"));
            builder.Append(" | ");
            builder.Append(EscapeTableCell(FormatCodeList(type.requiredOptions)));
            builder.Append(" | ");
            builder.Append(EscapeTableCell(FormatCodeList(type.optionalOptions)));
            builder.Append(" | ");
            builder.Append(type.supportsDataPatch ? "Yes" : "No");
            builder.Append(" | ");
            builder.Append(EscapeTableCell(FormatNotes(type.notes)));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
    }

    private static void AppendSafetySection(StringBuilder builder)
    {
        builder.AppendLine("## Safety Rules");
        builder.AppendLine();
        builder.AppendLine("- All asset paths use the `Assets/...` form.");
        builder.AppendLine("- Destructive or overwrite flows are guarded by `--force`, including `asset delete`, overwrite variants of `asset move`, `asset rename`, and `asset create`, `package remove`, plus destructive `scene patch` operations.");
        builder.AppendLine("- Use `scene inspect --with-values` before writing a scene patch spec.");
        builder.AppendLine("- Use `prefab inspect --with-values` before writing a prefab patch spec.");
        builder.AppendLine("- `asset create --type prefab` only creates an empty prefab root. Use `prefab create` for structured prefab authoring.");
        builder.AppendLine();
    }

    private static void AppendRelatedDocsSection(StringBuilder builder)
    {
        builder.AppendLine("## Related Docs");
        builder.AppendLine();
        builder.AppendLine("- [Architecture](architecture.md)");
        builder.AppendLine("- [Scene Spec](scene-spec.md)");
        builder.AppendLine("- [Prefab Spec](prefab-spec.md)");
        builder.AppendLine("- [Unity Package README](../unity-package/com.kinkeep.unity-cli-bridge/README.md)");
        builder.AppendLine();
    }

    private static string GetGroupTitle(CliCommandGroup group)
    {
        return group switch
        {
            CliCommandGroup.EditorControl => "Editor Control",
            CliCommandGroup.AssetWorkflows => "Asset Workflows",
            CliCommandGroup.SceneWorkflows => "Scene Workflows",
            CliCommandGroup.PrefabWorkflows => "Prefab Workflows",
            CliCommandGroup.PackageManagement => "Package Management",
            CliCommandGroup.MaterialWorkflows => "Material Workflows",
            CliCommandGroup.InstanceManagement => "Instance Management",
            CliCommandGroup.Diagnostics => "Diagnostics",
            _ => group.ToString(),
        };
    }

    private static string GetGroupSummary(CliCommandGroup group)
    {
        return group switch
        {
            CliCommandGroup.EditorControl => "Commands for editor state, compilation, play state, menus, arbitrary code execution, project-defined custom commands, and console access.",
            CliCommandGroup.AssetWorkflows => "Commands for querying, mutating, and creating assets under `Assets/...`.",
            CliCommandGroup.SceneWorkflows => "Commands for opening, inspecting, and patching saved scene assets.",
            CliCommandGroup.PrefabWorkflows => "Commands for inspecting, creating, and patching prefab assets.",
            CliCommandGroup.PackageManagement => "Commands for listing, adding, removing, and searching Unity packages.",
            CliCommandGroup.MaterialWorkflows => "Commands for inspecting and mutating material properties and texture slots.",
            CliCommandGroup.InstanceManagement => "Commands for selecting the active Unity project target from the local registry.",
            CliCommandGroup.Diagnostics => "Low-level commands for environment inspection and raw protocol debugging.",
            _ => string.Empty,
        };
    }

    private static string FormatModes(CliCommandDescriptor command)
    {
        var modes = new List<string>();
        if (command.CanUseLocal)
        {
            modes.Add("local");
        }

        if (command.CanUseLive)
        {
            modes.Add("live");
        }

        return modes.Count == 0 ? "-" : string.Join(", ", modes);
    }

    private static string FormatCodeList(IEnumerable<string> values)
    {
        string[] items = values.Where(value => !string.IsNullOrWhiteSpace(value)).ToArray();
        if (items.Length == 0)
        {
            return "-";
        }

        return string.Join(", ", items.Select(item => "`" + item + "`"));
    }

    private static string FormatNotes(IEnumerable<string> notes)
    {
        string[] items = notes.Where(note => !string.IsNullOrWhiteSpace(note)).ToArray();
        if (items.Length == 0)
        {
            return "-";
        }

        return string.Join("<br>", items);
    }

    private static string EscapeTableCell(string value)
    {
        return value.Replace("|", "\\|");
    }
}
